nname: Extraction Bor-Bi

on:
  workflow_dispatch:

jobs:
  unzipper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Décompresser le projet
        run: unzip projet.zip -d .

      - name: Fichiers de commit
        run: |
          git config --global user.name "Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Extraction automatique"
          git push
