name: Extraction Bor-Bi
on:
  workflow_dispatch:
jobs:
  decompresser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Decompresser le projet
        run: unzip projet.zip -d .
      - name: Commit files
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .
          git commit -m "Extraction automatique"
          git push
